# Generated by Django 5.1.5 on 2025-01-26 17:50

import django.db.models.deletion
import pet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cat', '0001_initial'),
        ('pet', '0002_remove_pet_age_pet_month_pet_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pet.pet')),
                ('species', models.CharField(max_length=100)),
                ('food_habit', models.TextField()),
                ('size', models.CharField(choices=[('Small', 'Small (<50g)'), ('Medium', 'Medium (50g-300g)'), ('Large', 'Large (>300g)')], max_length=10)),
                ('diet', models.CharField(choices=[('Herbivore', 'Herbivore (Fruits, seeds, vegetables)'), ('Omnivore', 'Omnivore (Fruits, seeds, insects)')], max_length=20)),
                ('description', models.TextField()),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='pet_images/cat_img/', validators=[pet.models.validate_image])),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='pet_images/cat_img/', validators=[pet.models.validate_image])),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='pet_images/cat_img/', validators=[pet.models.validate_image])),
                ('colors', models.ManyToManyField(related_name='birds', to='cat.catcolor')),
            ],
            bases=('pet.pet',),
        ),
    ]
