# Generated by Django 5.1.5 on 2025-01-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='diet',
            field=models.CharField(choices=[('Herbivore', 'Herbivore (Fruits, seeds, vegetables)'), ('Omnivore', 'Omnivore (Fruits, seeds, insects)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bird',
            name='size',
            field=models.CharField(choices=[('Small', 'Small (<50g)'), ('Medium (50g-300g)', 'Medium'), ('Large', 'Large (>300g)')], max_length=40),
        ),
    ]
