# Generated by Django 5.1.5 on 2025-01-27 09:01

import pet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0002_alter_bird_diet_alter_bird_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/bird_img/', validators=[pet.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='bird',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/bird_img/', validators=[pet.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='bird',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/bird_img/', validators=[pet.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='bird',
            name='size',
            field=models.CharField(choices=[('Small', 'Small (<50g)'), ('Medium', 'Medium (50g-300g)'), ('Large', 'Large (>300g)')], max_length=40),
        ),
    ]
