# Generated by Django 5.1.5 on 2025-01-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.AddField(
            model_name='pet',
            name='month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pet',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
