# Generated by Django 5.1.5 on 2025-01-31 10:11

import cloudinary.models
import pet.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_remove_pet_age_pet_month_pet_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image_1',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[pet.models.validate_image], verbose_name='image'),
        ),
    ]
