# Generated by Django 5.1.5 on 2025-01-31 10:38

import pet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image_1',
            field=models.ImageField(upload_to='pet_images', validators=[pet.models.validate_image]),
        ),
    ]
