# Generated by Django 5.1.5 on 2025-01-14 15:18

import cat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pet.pet')),
                ('food_habit', models.TextField()),
                ('is_potty_trained', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='pet_images/cat_img/', validators=[cat.models.validate_image])),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='pet_images/cat_img/', validators=[cat.models.validate_image])),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='pet_images/cat_img/', validators=[cat.models.validate_image])),
                ('colors', models.ManyToManyField(related_name='cats', to='cat.catcolor')),
            ],
            bases=('pet.pet',),
        ),
    ]
