# Generated by Django 5.1.5 on 2025-01-27 09:01

import pet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/dog_img/', validators=[pet.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/dog_img/', validators=[pet.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/dog_img/', validators=[pet.models.validate_image]),
        ),
    ]
